### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by nizarganteng** [jajosheni/instaBot#1]
instabot> Username: myusername
instabot> Password:
Connecting...
Traceback (most recent call last):
  File "app.py", line 818, in <module>
    login()
  File "app.py", line 67, in login
    if api.login():
  File "D:\instaBot-master\InstagramAPI\InstagramAPI.py", line 88, in login
    if (self.SendRequest('accounts/login/', self.generateSignature(json.dumps(data)), True)):
  File "D:\instaBot-master\InstagramAPI\InstagramAPI.py", line 353, in generateSignature
    return 'ig_sig_key_version=' + self.SIG_KEY_VERSION + '&signed_body=' + hmac.new(self.IG_SIG_KEY.encode('utf-8'), data.encode('utf-8'), hashlib.sha256).hexdigest() + '.' + parsedData
AttributeError: 'InstagramAPI' object has no attribute 'IG_SIG_KEY'

**Comment by jajosheni** [comment]
https://github.com/jajosheni/instaBot/blob/master/InstagramAPI/InstagramAPI.py#L35

Uncomment and find some working ig sig key on google
